name: irrigation_app
description: Automated Irrigation Monitoring App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  fl_chart: ^1.0.0
  intl: ^0.20.2
  socket_io_client: ^3.1.2
  connectivity_plus: ^6.1.4
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  permission_handler: ^12.0.0+1
  csv: ^6.0.0
  path_provider: ^2.1.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: fonts/Roboto-Light.ttf
  #         weight: 300
