// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk6zZArvDVX9O14YqGk-MXPzf3FhMgwms',
    appId: '1:1062152680017:web:91b29d8082e94bbd5dfe70',
    messagingSenderId: '1062152680017',
    projectId: 'irrigation-b9e5b',
    authDomain: 'irrigation-b9e5b.firebaseapp.com',
    storageBucket: 'irrigation-b9e5b.firebasestorage.app',
    measurementId: 'G-53PT8H04BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWQnow8cCDsES8wcKklqtApeEyluqYL-Y',
    appId: '1:1062152680017:android:c7e066dd31563f685dfe70',
    messagingSenderId: '1062152680017',
    projectId: 'irrigation-b9e5b',
    storageBucket: 'irrigation-b9e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJIjdLdZA6b05v4qrZBtjCyKf4OhWjC8A',
    appId: '1:1062152680017:ios:1ecff88638fe03c05dfe70',
    messagingSenderId: '1062152680017',
    projectId: 'irrigation-b9e5b',
    storageBucket: 'irrigation-b9e5b.firebasestorage.app',
    iosBundleId: 'com.example.irrigationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJIjdLdZA6b05v4qrZBtjCyKf4OhWjC8A',
    appId: '1:1062152680017:ios:1ecff88638fe03c05dfe70',
    messagingSenderId: '1062152680017',
    projectId: 'irrigation-b9e5b',
    storageBucket: 'irrigation-b9e5b.firebasestorage.app',
    iosBundleId: 'com.example.irrigationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk6zZArvDVX9O14YqGk-MXPzf3FhMgwms',
    appId: '1:1062152680017:web:40c3d96695b523c95dfe70',
    messagingSenderId: '1062152680017',
    projectId: 'irrigation-b9e5b',
    authDomain: 'irrigation-b9e5b.firebaseapp.com',
    storageBucket: 'irrigation-b9e5b.firebasestorage.app',
    measurementId: 'G-R6HW80FT0J',
  );
}
